config = {
    "width": 1280,
    "height": 960,
    "gain": 35,
    "exposure": .01,
    "whiteBalanceB": 150,
    "whiteBalanceR": 100,
    "gamma": 50,
    "brightness": 20,
    "flip": 0,
    "whiteBalance": True,
    "autoExposure": True,
    "autoGain": False,
    "max_auto_exp": 20,
    "max_auto_gain": 50,
    }